define([], function() {
  return {
    "PropertyPaneDescription": "Configure the My Enterprise Apps webpart settings.",
    "BasicGroupName": "Settings",
    "TitleFieldLabel": "Title",
    "SortOrderFieldLabel": "Sort Order",
    "SortOrderFieldDescription": "Enter app name keywords (one per line) to prioritize. Apps matching these terms will appear first in the specified order.",
    "ShowHiddenAppsLabel": "Show hidden apps (semi-transparent)",
    "ShowDefaultAppsLabel": "Show default apps",
    "LayoutPresetFieldLabel": "Size Preset",
    "LayoutPresetSmall": "Small",
    "LayoutPresetNormal": "Normal",
    "LayoutPresetLarge": "Large",
    "LayoutPresetHuge": "Extra Large",
    "LayoutPresetCustom": "Custom",
    "IconSizeFieldLabel": "Icon Size",
    "TextSizeFieldLabel": "Text Size",
    "AppSpacingFieldLabel": "Space Between Apps",
    "DefaultTitle": "My Apps",
    "AllAppsLabel": "All Apps",
    "NoAppsFound": "No apps found",
    "FilterAppsLabel": "Filter apps",
    "FilterAppsPlaceholder": "Search apps",
    "ClearFilterLabel": "Clear filter",
    "CloseFilterLabel": "Close filter",
    "NoFilterResults": "No apps match your filter",
    "ErrorLoading": "Error loading apps",
    "AppLocalEnvironmentSharePoint": "The app is running on your local environment as SharePoint web part",
    "AppLocalEnvironmentTeams": "The app is running on your local environment as Microsoft Teams app",
    "AppLocalEnvironmentOffice": "The app is running on your local environment in office.com",
    "AppLocalEnvironmentOutlook": "The app is running on your local environment in Outlook",
    "AppSharePointEnvironment": "The app is running on SharePoint page",
    "AppTeamsTabEnvironment": "The app is running in Microsoft Teams",
    "AppOfficeEnvironment": "The app is running in office.com",
    "AppOutlookEnvironment": "The app is running in Outlook",
    "UnknownEnvironment": "The app is running in an unknown environment"
  }
});
