define([], function() {
  return {
    "PropertyPaneDescription": "Configure the My Enterprise Apps webpart settings.",
    "BasicGroupName": "Settings",
    "DetailViewGroupName": "App detail view",
    "TitleFieldLabel": "Title",
    "SortOrderFieldLabel": "Sort Order",
    "SortOrderFieldDescription": "Enter app name keywords (one per line) to prioritize. Apps matching these terms will appear first in the specified order.",
    "ShowHiddenAppsLabel": "Show hidden apps (semi-transparent)",
    "ShowDefaultAppsLabel": "Show default apps",
    "CacheGroupName": "Browser cache",
    "EnableCacheLabel": "Enable browser cache",
    "CacheDurationFieldLabel": "Cache duration (minutes)",
    "DefaultAppsGroupName": "Default apps",
    "DisplayInternalNotesLabel": "Display internal notes",
    "DisplayAppIdentifiersLabel": "Display app ID and service principal ID",
    "DisplayOAuthScopesLabel": "Display OAuth scopes",
    "EnableDetailViewLabel": "Enable app detail view",
    "LayoutPresetFieldLabel": "Size Preset",
    "LayoutPresetSmall": "Small",
    "LayoutPresetNormal": "Normal",
    "LayoutPresetLarge": "Large",
    "LayoutPresetHuge": "Extra Large",
    "LayoutPresetCustom": "Custom",
    "IconSizeFieldLabel": "Icon Size",
    "TextSizeFieldLabel": "Text Size",
    "AppSpacingFieldLabel": "Space Between Apps",
    "DefaultTitle": "My Apps",
    "AllAppsLabel": "Open My Apps",
    "NoAppsFound": "No apps found",
    "FilterAppsLabel": "Filter apps",
    "FilterAppsPlaceholder": "Search apps",
    "ClearFilterLabel": "Clear filter",
    "CloseFilterLabel": "Close filter",
    "NoFilterResults": "No apps match your filter",
    "ErrorLoading": "Error loading apps",
    "NotAvailable": "Not available",
    "BackToResults": "Back to search results",
    "OpenApp": "Open app",
    "AppId": "App ID",
    "ServicePrincipalId": "Service principal ID",
    "Homepage": "Homepage",
    "Description": "Description",
    "SingleSignOn": "Single sign-on",
    "TermsOfService": "Terms of Service",
    "OpenTermsOfService": "Open Terms of Service",
    "OAuthScopes": "Available OAuth scopes",
    "Resources": "Resources",
    "VerifiedPublisher": "Verified publisher",
    "SamlSso": "SAML",
    "OpenIdConnectSso": "OpenID Connect",
    "PasswordSso": "Password SSO",
    "LinkedSso": "Linked SSO",
    "SsoNotSupported": "Not supported",
    "AppLocalEnvironmentSharePoint": "The app is running on your local environment as SharePoint web part",
    "AppLocalEnvironmentTeams": "The app is running on your local environment as Microsoft Teams app",
    "AppLocalEnvironmentOffice": "The app is running on your local environment in office.com",
    "AppLocalEnvironmentOutlook": "The app is running on your local environment in Outlook",
    "AppSharePointEnvironment": "The app is running on SharePoint page",
    "AppTeamsTabEnvironment": "The app is running in Microsoft Teams",
    "AppOfficeEnvironment": "The app is running in office.com",
    "AppOutlookEnvironment": "The app is running in Outlook",
    "UnknownEnvironment": "The app is running in an unknown environment"
  }
});
