declare interface IMyEnterpriseAppsWebPartStrings {
  PropertyPaneDescription: string;
  BasicGroupName: string;
  DetailViewGroupName: string;
  TitleFieldLabel: string;
  SortOrderFieldLabel: string;
  SortOrderFieldDescription: string;
  ShowHiddenAppsLabel: string;
  ShowDefaultAppsLabel: string;
  CacheGroupName: string;
  EnableCacheLabel: string;
  CacheDurationFieldLabel: string;
  DefaultAppsGroupName: string;
  DisplayInternalNotesLabel: string;
  DisplayAppIdentifiersLabel: string;
  DisplayOAuthScopesLabel: string;
  EnableDetailViewLabel: string;
  LayoutPresetFieldLabel: string;
  LayoutPresetSmall: string;
  LayoutPresetNormal: string;
  LayoutPresetLarge: string;
  LayoutPresetHuge: string;
  LayoutPresetCustom: string;
  IconSizeFieldLabel: string;
  TextSizeFieldLabel: string;
  AppSpacingFieldLabel: string;
  DefaultTitle: string;
  AllAppsLabel: string;
  NoAppsFound: string;
  FilterAppsLabel: string;
  FilterAppsPlaceholder: string;
  ClearFilterLabel: string;
  CloseFilterLabel: string;
  NoFilterResults: string;
  ErrorLoading: string;
  NotAvailable: string;
  BackToResults: string;
  OpenApp: string;
  AppId: string;
  ServicePrincipalId: string;
  Homepage: string;
  Description: string;
  SingleSignOn: string;
  TermsOfService: string;
  OpenTermsOfService: string;
  OAuthScopes: string;
  Resources: string;
  VerifiedPublisher: string;
  SamlSso: string;
  OpenIdConnectSso: string;
  PasswordSso: string;
  LinkedSso: string;
  SsoNotSupported: string;
  AppLocalEnvironmentSharePoint: string;
  AppLocalEnvironmentTeams: string;
  AppLocalEnvironmentOffice: string;
  AppLocalEnvironmentOutlook: string;
  AppSharePointEnvironment: string;
  AppTeamsTabEnvironment: string;
  AppOfficeEnvironment: string;
  AppOutlookEnvironment: string;
  UnknownEnvironment: string;
}

declare module 'MyEnterpriseAppsWebPartStrings' {
  const strings: IMyEnterpriseAppsWebPartStrings;
  export = strings;
}
