define([], function() {
  return {
    "PropertyPaneDescription": "Configureer de instellingen voor de My Enterprise Apps webpart.",
    "BasicGroupName": "Instellingen",
    "DetailViewGroupName": "App-detailweergave",
    "TitleFieldLabel": "Titel",
    "SortOrderFieldLabel": "Sorteervolgorde",
    "SortOrderFieldDescription": "Voer trefwoorden voor app-namen in (één per regel) om prioriteit te geven. Apps die overeenkomen met deze termen verschijnen eerst in de opgegeven volgorde.",
    "ShowHiddenAppsLabel": "Toon verborgen apps (semi-transparant)",
    "ShowDefaultAppsLabel": "Toon standaardapps",
    "CacheGroupName": "Browsercache",
    "EnableCacheLabel": "Browsercache inschakelen",
    "CacheDurationFieldLabel": "Cacheduur (minuten)",
    "DefaultAppsGroupName": "Standaardapps",
    "DisplayInternalNotesLabel": "Interne notities weergeven",
    "DisplayAppIdentifiersLabel": "App-id en service principal-id weergeven",
    "DisplayOAuthScopesLabel": "OAuth-scopes weergeven",
    "EnableDetailViewLabel": "App-detailweergave inschakelen",
    "LayoutPresetFieldLabel": "Groottevoorinstelling",
    "LayoutPresetSmall": "Klein",
    "LayoutPresetNormal": "Normaal",
    "LayoutPresetLarge": "Groot",
    "LayoutPresetHuge": "Extra groot",
    "LayoutPresetCustom": "Aangepast",
    "IconSizeFieldLabel": "Pictogramgrootte",
    "TextSizeFieldLabel": "Tekstgrootte",
    "AppSpacingFieldLabel": "Afstand tussen apps",
    "DefaultTitle": "Mijn apps",
    "AllAppsLabel": "Mijn apps openen",
    "NoAppsFound": "Geen apps gevonden",
    "FilterAppsLabel": "Apps filteren",
    "FilterAppsPlaceholder": "Apps zoeken",
    "ClearFilterLabel": "Filter wissen",
    "CloseFilterLabel": "Filter sluiten",
    "NoFilterResults": "Geen apps komen overeen met uw filter",
    "ErrorLoading": "Fout bij het laden van apps",
    "NotAvailable": "Niet beschikbaar",
    "BackToResults": "Terug naar zoekresultaten",
    "OpenApp": "App openen",
    "AppId": "App-id",
    "ServicePrincipalId": "Service principal-id",
    "Homepage": "Startpagina",
    "Description": "Beschrijving",
    "SingleSignOn": "Single sign-on",
    "TermsOfService": "Voorwaarden",
    "OpenTermsOfService": "Voorwaarden openen",
    "OAuthScopes": "Beschikbare OAuth-scopes",
    "Resources": "Informatie",
    "VerifiedPublisher": "Geverifieerde uitgever",
    "SamlSso": "SAML",
    "OpenIdConnectSso": "OpenID Connect",
    "PasswordSso": "Wachtwoord-SSO",
    "LinkedSso": "Gekoppelde SSO",
    "SsoNotSupported": "Niet ondersteund",
    "AppLocalEnvironmentSharePoint": "De app draait in uw lokale omgeving als SharePoint-webpart",
    "AppLocalEnvironmentTeams": "De app draait in uw lokale omgeving als Microsoft Teams-app",
    "AppLocalEnvironmentOffice": "De app draait in uw lokale omgeving in office.com",
    "AppLocalEnvironmentOutlook": "De app draait in uw lokale omgeving in Outlook",
    "AppSharePointEnvironment": "De app draait op een SharePoint-pagina",
    "AppTeamsTabEnvironment": "De app draait in Microsoft Teams",
    "AppOfficeEnvironment": "De app draait in office.com",
    "AppOutlookEnvironment": "De app draait in Outlook",
    "UnknownEnvironment": "De app draait in een onbekende omgeving"
  }
});
